title: hee's 개발 블로그
email: http://gmail.com/hee980313@gmail.com
description: "Junior backend developer"
author: ""
baseurl: ""
url: https://heejung-gjt.github.io

# Social Profiles
github_username: heejung-gjt

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

nav:
  About:
    - "/about/"
  Github Project:
    - "https://github.com/heejung-gjt"
